[features]
seeds = false
skip-lint = false
[programs.devnet]
crowdfunding = "DeSg615KHp13ghYULjsBrXjvUosYYenSPKXqyHawxY2f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sanwaniii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
